### PR TITLE
Added wipe button functionality to work with servers and dms

### PR DESCRIPTION
**Pull request by apolayil**
Just a note, this is my first time doing javascript, so I don't know much about it. 

About the pull request: 
- When no server ID is given, it fetches information about the channel and handles it appropriately, this means that when using the wipe button, it can handle both servers and dms.

### CODE REVIEW

**Comment by ImNotIcon** [comment]
The formatting also gave me a hard time to work with haha

I don't quite understand what this commit does. The problem with wipe archive is it doesn't have access to the guild ids. The index.json file is of type {channelId1: channelName1, ...} so the program just assumes that they are all dm channels.

Only way to fix this would be to pass the guild ids as well. We can do so by selecting the messages folder as a whole and looping through all the folders to get the guild id from each channel.json. If "guildId" exists as a key it's a server channel, if not it's a dm channel.

**Comment by apolayil** [comment]
Yeah, I'm also pretty new to git, so I really wanted to smash my head in haha.
I think you're plan is better in the long term, since this adds an additional https request to retrieve information about the channel from discord which may not be favoured(?)

`const CHANNEL_INFO_URL = `https://discord.com/api/v9/channels/${this.options.channelId}`
So discord has a way to request information about the channel (above), given the channelId. I used this and noticed Discord had `type 0` and `type 1` to differentiate between server channels and DM channels, so using that information I did what the code did before with "`@me else server`", just this time it was `type 0` and `type 1` and assigned it the correct `API_SEARCH_URL`. This is done only if a server ID/@me isn't given. 

I hope this makes sense, also its probably more confusing because I accidentally added an extra indent for the if else statement. I did test the code myself and it worked perfectly, but yeah I don't know enough about javascript to know if its a viable solution :/

**Comment by ImNotIcon** [comment]
So this link returns the channel info and you get the guild id that way, now I do get it. I guess that'd work, I'll do my own research soon and see if there's some better way to do it. I think there is a way to search without the guild id, we definitely don't need it for deleting messages:
`const API_DELETE_URL = \`https://discord.com/api/v9/channels/${message.channel_id}/messages/${message.id}\`;`

**Comment by ImNotIcon** [comment]
Fixed wipe archive with servers in db69f9f

I made a different function for it so it's more organized. It sets the server id to 'null' as a placeholder. I tried not to complicate it with checking channel types by setting the guildId to resp.guild_id or '@me' if it's undefined.

**Pull request closed without merging**
